### ISSUE TITLE
kali 

### ISSUE THREAD

**Issue by lianfeng30** [OrOneEqualsOne/reconned#2]
("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)
Process DNSdumpster-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "bin/Sublist3r/sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "bin/Sublist3r/sublist3r.py", line 634, in enumerate
    token = self.get_csrftoken(resp)
  File "bin/Sublist3r/sublist3r.py", line 629, in get_csrftoken
    token = csrf_regex.findall(resp)[0]
TypeError: expected string or buffer

**Comment by OrOneEqualsOne** [comment]
lianfeng30, Thank you for reporting these issues and your patience. I have written in additional error checking and conducted additional testing  - can you please check if you receive the same issue with the updated script?

**Comment by lianfeng30** [comment]
oh... thanks
but error also:

Running Command: python2 bin/domain/enumall.py bytedance.net
Traceback (most recent call last):
  File "bin/domain/enumall.py", line 26, in <module>
    from recon.core import base
ImportError: No module named recon.core

enumall Complete
rm: bytedance_net*: No such file or directory

what i do?

**Comment by OrOneEqualsOne** [comment]
Thanks for troubleshooting - the Enumall tool requires Recon-ng (usually included in Kali) can you please run “apt-get update && apt-get install recon-ng” to install Recon-ng and rerun the script. If that works I will add the command to the install script. Thanks again!

**Comment by lianfeng30** [comment]
e..
i'm Mac ...  how to install recon-ng?

**Comment by OrOneEqualsOne** [comment]
I believe at least EyeWitness may require Kali Linux or Debian - which may require you to run the script in a Debian VM (VM Ware or Virtual Box). More info on installing recon-ng on other platforms can be found here: https://bitbucket.org/LaNMaSteR53/recon-ng/wiki/Usage%20Guide

**Comment by lianfeng30** [comment]
Okay, thanks again
